AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: .NET Messaging Service with Azure SignalR Integration

Resources:
  MessagingApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ # Path to your application code
      Handler: MessagingBackend::MessagingBackend.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnet8
      MemorySize: 512
      Timeout: 30
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          MONGO_CONNECTION_STRING: "mongodb+srv://ddmann2004:9kt1LQi62AMBcXDW@cluster0.gzmfmz9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
          MONGO_DATABASE_NAME: "Capstone"
          SIGNALR_CONNECTION_STRING: "Endpoint=https://capstone.service.signalr.net;AccessKey=CGrYlHTM1cQVGyEFNeky1Kt3JRbrR3MKt9olzt0hjWcvs8JgtvO6JQQJ99ALACYeBjFXJ3w3AAAAASRSIpOO;Version=1.0;"
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for the Messaging Service"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
