AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: .NET Messaging Service

Resources:
  MessagingApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: MessagingBackend::MessagingBackend.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnet8
      MemorySize: 512
      Timeout: 30
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for the Messaging Service"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
