AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WebSocket-based live messaging system with AWS Lambda

Resources:
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: "WebSocketApi"
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketConnectFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: WebSocketConnectFunction::HandleConnectAsync
      Runtime: dotnet6
      CodeUri: ./src
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable

  WebSocketDisconnectFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: WebSocketDisconnectFunction::HandleDisconnectAsync
      Runtime: dotnet6
      CodeUri: ./src
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable

  WebSocketSendMessageFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: WebSocketSendMessageFunction::HandleSendMessageAsync
      Runtime: dotnet6
      CodeUri: ./src
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable

  WebSocketApiGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:!GetAtt WebSocketConnectFunction.Arn

  WebSocketRouteConnect:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "$connect"
      AuthorizationType: NONE
      Target: !Sub "integrations/${WebSocketApiGatewayIntegration}"

  WebSocketRouteDisconnect:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "$disconnect"
      AuthorizationType: NONE
      Target: !Sub "integrations/${WebSocketApiGatewayIntegration}"

  WebSocketRouteSendMessage:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: "sendmessage"
      AuthorizationType: NONE
      Target: !Sub "integrations/${WebSocketApiGatewayIntegration}"

  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "WebSocketConnections"
      AttributeDefinitions:
        - AttributeName: "connectionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "connectionId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  WebSocketApiUrl:
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com"
    Description: "WebSocket API URL"
