AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for UserService

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    LoggingConfig:
      LogFormat: JSON

Resources:
  CreatePost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/HelloWorld/
      Handler: HelloWorld::HelloWorld.Function::CreatePost
      Runtime: dotnet8
      Architectures:
      - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        CreatePostEvent:
          Type: Api
          Properties:
            Path: /CreatePost
            Method: POST

  GetPosts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/HelloWorld/
      Handler: HelloWorld::HelloWorld.Function::GetPosts
      Runtime: dotnet8
      Architectures:
      - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        GetPostsEvent:
          Type: Api
          Properties:
            Path: /GetPosts
            Method: GET
            RequestParameters:
              method.request.querystring.page:
                Required: false
                Caching: false

  EditPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/HelloWorld/
      Handler: HelloWorld::HelloWorld.Function::EditPost
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        EditPostEvent:
          Type: Api
          Properties:
            Path: /EditPost/{id}
            Method: PUT

  GetPostById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/HelloWorld/
      Handler: HelloWorld::HelloWorld.Function::GetPost
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        GetPostByIdEvent:
          Type: Api
          Properties:
            Path: /GetPost/{id}
            Method: GET

  GetUserPosts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/HelloWorld/
      Handler: HelloWorld::HelloWorld.Function::GetUserPosts
      Runtime: dotnet8
      Timeout: 30
      Events:
        GetUserPostsApi:
          Type: Api
          Properties:
            Path: /GetPosts/{userId}
            Method: GET
            RequestParameters:
              - method.request.querystring.page: false  


Outputs:
  PostsApiEndpoint:
    Description: API Gateway endpoint URL for Prod stage for Post functions
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  
  CreatePostFunctionArn:
    Description: ARN of the CreatePost Lambda function
    Value: !GetAtt CreatePost.Arn

  GetPostsFunctionArn:
    Description: ARN of the GetPosts Lambda function
    Value: !GetAtt GetPosts.Arn

  EditPostFunctionArn:
    Description: ARN of the EditPost Lambda function
    Value: !GetAtt EditPost.Arn

  GetPostByIdFunctionArn:
    Description: ARN of the GetPostById Lambda function
    Value: !GetAtt GetPostById.Arn

 GetUserPostsArn:
    Description: ARN of the GetUserPosts Lambda function
    Value: !GetAtt GetUserPosts.Arn

  CreatePostIamRole:
    Description: Implicit IAM Role created for CreatePost function
    Value: !GetAtt CreatePostRole.Arn

  GetPostsIamRole:
    Description: Implicit IAM Role created for GetPosts function
    Value: !GetAtt GetPostsRole.Arn

  EditPostIamRole:
    Description: Implicit IAM Role created for EditPost function
    Value: !GetAtt EditPostRole.Arn

  GetPostByIdIamRole:
    Description: Implicit IAM Role created for GetPostById function
    Value: !GetAtt GetPostByIdRole.Arn

  GetUserPostsIamRole:
    Description: Implicit IAM Role created for GetUserPosts function
    Value: !GetAtt GetUserPostsRole.Arn
