AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for UserService

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    LoggingConfig:
      LogFormat: JSON

Resources:
  CreatePost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/HelloWorld/
      Handler: HelloWorld::HelloWorld.Function::CreatePost
      Runtime: dotnet8
      Architectures:
      - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        CreatePostEvent:
          Type: Api
          Properties:
            Path: /CreatePost
            Method: POST

Outputs:
  PostsApiEndpoint:
    Description: API Gateway endpoint URL for Prod stage for Post function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/CreatePost/"

  CreatePostFunctionArn:
    Description: ARN of the CreatePost Lambda function
    Value: !GetAtt CreatePost.Arn

  CreatePostIamRole:
    Description: Implicit IAM Role created for CreatePost function
    Value: !GetAtt CreatePostRole.Arn
